### ISSUE TITLE
Link 컴포넌트 반응형 높이 수정

### ISSUE THREAD

**Issue by Sunjae95** [DaleStudy/leaderboard#121]
## 요구사항
<img width="307" alt="Image" src="https://github.com/user-attachments/assets/3e42cf37-5dab-418a-9e5e-739b4c9a8ef7" />

반응형으로 인해 text 밀림 현상을 해결합니다.

**Comment by DaleSeo** [comment]
@Sunjae95 요거 혹시 해결된 이슈일까요? 아직 이슈가 열려있어서 여쭙니당! 해결된 이슈라면 닫아주세요.

**Comment by Sunjae95** [comment]
@DaleSeo 아직 해결이 안됐네요. 잊고있었습니다..! ㅎㅎ

**Comment by Sunjae95** [comment]
작업 전 쟤가 생각하는 해결방법 2가지중 고민이 되는데요.
1. 부모,조상 dom의 min-width값을 주어 해결한다.
2. link컴포넌트의 min-width값을 주어 해결한다.

페이지(조상 dom)의 min-width 값을 추가하여 짤리지 않도록 하는 것이 별도의 컴포넌트 수정이 필요없어서 유리해보여요.
물론 디자인과 협의가 있어야하는 부분이라 정하면 좋을거 같아서 1번 방법이 좋아보입니다.

두경우가 아닌 다른 더 좋은 방법이 있을까요?

**Comment by yolophg** [comment]
선재님, 아이디어 감사합니다.

두 가지 해결방법 모두 코드와 함께 살펴봤는데, 더 나은 방향이 있을 것 같습니다. 아래처럼 버튼의 정렬 방식만 수직으로 바꾸는 건 어떨까요?
디자인 쪽에서도 모바일 UX를 고려했을 때 저희 서비스에 더 좋은 업데이트가 될 것 같기도 해서요. 

![Image](https://github.com/user-attachments/assets/f6d33712-91f7-4311-9293-72327299d52e)

모바일 화면에서는 버튼들을 수직으로 쌓아서, 터치 영역도 좀 더 확대하고, 텍스트 밀림 현상도 해결하고, 컴포넌트 재사용성도 유지하면 좋을 것 같아서요!

스타일 파일에선 아래 코드로만 변경해주시면 될 것 같아요:
```css
.buttons {
  & > div {
    @media (모바일 일 때) {
      flex-direction: column;
      row-gap: 10px;
      min-width: 100%;
    }
  }
}
```
피그마에도 업데이트 해두었으니 참고해주세요!
[피그마 링크](https://www.figma.com/design/j4gGV8VkvpOCL1UYpP99rt?node-id=2429-441#1156610708)
